spring:
  application:
    name: workflow-management-system

  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_orchestrator_db
    username: workflow_orchestrator_user
    password: workflow_orchestrator_password

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: workflow-workers
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: orchestrator.execution.event
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: manual

workflow:
  execution:
    topic: workflow.step-executions
    topic-partitions: 3
